// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOption0s have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzPpJ8WzyRn9bx1DDnMCiP6z6_d8gp6Cw',
    appId: '1:119299730334:web:106ee6de6adb5ab635c48f',
    messagingSenderId: '119299730334',
    projectId: 'firefly-618c5',
    authDomain: 'firefly-618c5.firebaseapp.com',
    databaseURL: 'https://firefly-618c5-default-rtdb.firebaseio.com',
    storageBucket: 'firefly-618c5.appspot.com',
    measurementId: 'G-DDKYEDJEF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5-edMJHA5B0uibv0Oxyiv7ozp172D7Mc',
    appId: '1:119299730334:android:01a5a3e9d6e0dd6535c48f',
    messagingSenderId: '119299730334',
    projectId: 'firefly-618c5',
    databaseURL: 'https://firefly-618c5-default-rtdb.firebaseio.com',
    storageBucket: 'firefly-618c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSkrgt7tiRZeAKyEwnZ34KpsK_SQbuxrI',
    appId: '1:119299730334:ios:7ad5f9ff96c4cf4335c48f',
    messagingSenderId: '119299730334',
    projectId: 'firefly-618c5',
    databaseURL: 'https://firefly-618c5-default-rtdb.firebaseio.com',
    storageBucket: 'firefly-618c5.appspot.com',
    iosClientId: '119299730334-59rv98mi5qvos3ffg65bl7t6c4pngaff.apps.googleusercontent.com',
    iosBundleId: 'com.example.firefly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSkrgt7tiRZeAKyEwnZ34KpsK_SQbuxrI',
    appId: '1:119299730334:ios:7ad5f9ff96c4cf4335c48f',
    messagingSenderId: '119299730334',
    projectId: 'firefly-618c5',
    databaseURL: 'https://firefly-618c5-default-rtdb.firebaseio.com',
    storageBucket: 'firefly-618c5.appspot.com',
    iosClientId: '119299730334-59rv98mi5qvos3ffg65bl7t6c4pngaff.apps.googleusercontent.com',
    iosBundleId: 'com.example.firefly',
  );
}
